### ISSUE TITLE
Errors when response body example is missing

### ISSUE THREAD

**Issue by postatum** [bastuijnman/leanapi#1]
Hi! Thanks for a nice lib!

I get an error when using the tool like so:

```
wget -O api.raml https://raw.githubusercontent.com/raml-org/raml-examples/master/typesystem/simple.raml
leanapi api.raml
```
```
/usr/lib/node_modules/leanapi/src/parsers/raml.js:146
                    body: body.example().value(),
                                        ^

TypeError: Cannot read property 'value' of null
    at examples.response.body.map (/usr/lib/node_modules/leanapi/src/parsers/raml.js:146:41)
    at Array.map (<anonymous>)
    at Object.parseResponse (/usr/lib/node_modules/leanapi/src/parsers/raml.js:137:39)
    at Array.map (<anonymous>)
    at getRequestResponses (/usr/lib/node_modules/leanapi/src/parsers/raml.js:38:22)
    at Object.parseCall (/usr/lib/node_modules/leanapi/src/parsers/raml.js:104:24)
    at Array.map (<anonymous>)
    at resources.map (/usr/lib/node_modules/leanapi/src/parsers/raml.js:86:39)
    at Array.map (<anonymous>)
    at Object.parseResources (/usr/lib/node_modules/leanapi/src/parsers/raml.js:75:26)
```

**Comment by bastuijnman** [comment]
Hi,

So sorry for the late reply, for some reason this never showed up in my notifications.

This seems like some sort of oversight in the parser, I'll look into it and will try to fix. The parser is overdue for an overhaul anyway.

Cheers.

Bas

**Comment by bastuijnman** [comment]
Version 1.5.0 should resolve the issue that you're having, in addition to updating a lot of the libraries used within the project.
